icons = "awesome"

[[block]]
block ="music"
player = "mpd"
buttons = ["play", "next"]
max_width = 36

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
